export const LanguagesMixin = {
  data () {
    return {
      languages: [      
        { name: 'Abkhaz', label: 'Аҧсуа', value: 'abk' },
        { name: 'Afar', label: 'Afaraf', value: 'aar' },
        { name: 'Afrikaans', label: 'Afrikaans', value: 'afr' },
        { name: 'Akan', label: 'Akan', value: 'aka' },
        { name: 'Albanian', label: 'Shqip', value: 'sqi' },
        { name: 'Amharic', label: 'አማርኛ', value: 'amh' },
        { name: 'Arabic', label: 'العربية', value: 'ara' },
        { name: 'Aragonese', label: 'Aragonés', value: 'arg' },
        { name: 'Armenian', label: 'Հայերեն', value: 'hye' },
        { name: 'Assamese', label: 'অসমীয়া', value: 'asm' },
        { name: 'Avaric', label: 'Авар', value: 'ava' },
        { name: 'Avestan', label: 'avesta', value: 'ave' },
        { name: 'Aymara', label: 'Aymar', value: 'aym' },
        { name: 'Azerbaijani', label: 'Azərbaycanca', value: 'aze' },
        { name: 'Bambara', label: 'Bamanankan', value: 'bam' },
        { name: 'Bashkir', label: 'Башҡортса', value: 'bak' },
        { name: 'Basque', label: 'Euskara', value: 'eus' },
        { name: 'Belarusian', label: 'Беларуская', value: 'bel' },
        { name: 'Bengali', label: 'বাংলা', value: 'ben' },
        { name: 'Bihari', label: 'भोजपुरी', value: 'bih' },
        { name: 'Bislama', label: 'Bislama', value: 'bis' },
        { name: 'Bosnian', label: 'Bosanski', value: 'bos' },
        { name: 'Breton', label: 'Brezhoneg', value: 'bre' },
        { name: 'Bulgarian', label: 'Български', value: 'bul' },
        { name: 'Burmese', label: 'မြန်မာဘာသာ', value: 'mya' },
        { name: 'Catalan', label: 'Català', value: 'cat' },
        { name: 'Chamorro', label: 'Chamoru', value: 'cha' },
        { name: 'Chechen', label: 'Нохчийн', value: 'che' },
        { name: 'Chichewa', label: 'Chichewa', value: 'nya' },
        { name: 'Chinese', label: '中文', value: 'zho' },
        { name: 'Chuvash', label: 'Чӑвашла', value: 'chv' },
        { name: 'Cornish', label: 'Kernewek', value: 'cor' },
        { name: 'Corsican', label: 'Corsu', value: 'cos' },
        { name: 'Cree', label: 'ᓀᐦᐃᔭᐍᐏᐣ', value: 'cre' },
        { name: 'Croatian', label: 'Hrvatski', value: 'hrv' },
        { name: 'Czech', label: 'Čeština', value: 'ces' },
        { name: 'Danish', label: 'Dansk', value: 'dan' },
        { name: 'Divehi', label: 'Divehi', value: 'div' },
        { name: 'Dutch', label: 'Nederlands', value: 'nld' },
        { name: 'Dzongkha', label: 'རྫོང་ཁ', value: 'dzo' },
        { name: 'English', label: 'English', value: 'eng' },
        { name: 'Esperanto', label: 'Esperanto', value: 'epo' },
        { name: 'Estonian', label: 'Eesti', value: 'est' },
        { name: 'Ewe', label: 'Eʋegbe', value: 'ewe' },
        { name: 'Faroese', label: 'Føroyskt', value: 'fao' },
        { name: 'Fijian', label: 'Na Vosa Vaka-Viti', value: 'fij' },
        { name: 'Finnish', label: 'Suomi', value: 'fin' },
        { name: 'French', label: 'Français', value: 'fra' },
        { name: 'Fula', label: 'Fulfulde', value: 'ful' },
        { name: 'Galician', label: 'Galego', value: 'glg' },
        { name: 'Georgian', label: 'ქართული', value: 'kat' },
        { name: 'German', label: 'Deutsch', value: 'deu' },
        { name: 'Greek', label: 'Ελληνικά', value: 'ell' },
        { name: 'Guaraní', label: 'Avañe\'ẽ', value: 'grn' },
        { name: 'Gujarati', label: 'ગુજરાતી', value: 'guj' },
        { name: 'Haitian', label: 'Kreyòl Ayisyen', value: 'hat' },
        { name: 'Hausa', label: 'هَوُسَ', value: 'hau' },
        { name: 'Hebrew', label: 'עברית', value: 'heb' },
        { name: 'Herero', label: 'Otjiherero', value: 'her' },
        { name: 'Hindi', label: 'हिन्दी', value: 'hin' },
        { name: 'Hiri Motu', label: 'Hiri Motu', value: 'hmo' },
        { name: 'Hungarian', label: 'Magyar', value: 'hun' },
        { name: 'Interlingua', label: 'Interlingua', value: 'ina' },
        { name: 'Indonesian', label: 'Bahasa Indonesia', value: 'ind' },
        { name: 'Interlingue', label: 'Interlingue', value: 'ile' },
        { name: 'Irish', label: 'Gaeilge', value: 'gle' },
        { name: 'Igbo', label: 'Igbo', value: 'ibo' },
        { name: 'Inupiaq', label: 'Iñupiak', value: 'ipk' },
        { name: 'Ido', label: 'Ido', value: 'ido' },
        { name: 'Icelandic', label: 'Íslenska', value: 'isl' },
        { name: 'Italian', label: 'Italiano', value: 'ita' },
        { name: 'Inuktitut', label: 'ᐃᓄᒃᑎᑐᑦ', value: 'iku' },
        { name: 'Japanese', label: '日本語', value: 'jpn' },
        { name: 'Javanese', label: 'Basa Jawa', value: 'jav' },
        { name: 'Kalaallisut', label: 'Kalaallisut', value: 'kal' },
        { name: 'Kannada', label: 'ಕನ್ನಡ', value: 'kan' },
        { name: 'Kanuri', label: 'Kanuri', value: 'kau' },
        { name: 'Kashmiri', label: 'كشميري', value: 'kas' },
        { name: 'Kazakh', label: 'Қазақша', value: 'kaz' },
        { name: 'Khmer', label: 'ភាសាខ្មែរ', value: 'khm' },
        { name: 'Kikuyu', label: 'Gĩkũyũ', value: 'kik' },
        { name: 'Kinyarwanda', label: 'Kinyarwanda', value: 'kin' },
        { name: 'Kyrgyz', label: 'Кыргызча', value: 'kir' },
        { name: 'Komi', label: 'Коми', value: 'kom' },
        { name: 'Kongo', label: 'Kongo', value: 'kon' },
        { name: 'Korean', label: '한국어', value: 'kor' },
        { name: 'Kurdish', label: 'Kurdî', value: 'kur' },
        { name: 'Kwanyama', label: 'Kuanyama', value: 'kua' },
        { name: 'Latin', label: 'Latina', value: 'lat' },
        { name: 'Luxembourgish', label: 'Lëtzebuergesch', value: 'ltz' },
        { name: 'Ganda', label: 'Luganda', value: 'lug' },
        { name: 'Limburgish', label: 'Limburgs', value: 'lim' },
        { name: 'Lingala', label: 'Lingála', value: 'lin' },
        { name: 'Lao', label: 'ພາສາລາວ', value: 'lao' },
        { name: 'Lithuanian', label: 'Lietuvių', value: 'lit' },
        { name: 'Luba-Katanga', label: 'Tshiluba', value: 'lub' },
        { name: 'Latvian', label: 'Latviešu', value: 'lav' },
        { name: 'Manx', label: 'Gaelg', value: 'glv' },
        { name: 'Macedonian', label: 'Македонски', value: 'mkd' },
        { name: 'Malagasy', label: 'Malagasy', value: 'mlg' },
        { name: 'Malay', label: 'Bahasa Melayu', value: 'msa' },
        { name: 'Malayalam', label: 'മലയാളം', value: 'mal' },
        { name: 'Maltese', label: 'Malti', value: 'mlt' },
        { name: 'Māori', label: 'Māori', value: 'mri' },
        { name: 'Marathi', label: 'मराठी', value: 'mar' },
        { name: 'Marshallese', label: 'Kajin M̧ajeļ', value: 'mah' },
        { name: 'Mongolian', label: 'Монгол', value: 'mon' },
        { name: 'Nauru', label: 'Dorerin Naoero', value: 'nau' },
        { name: 'Navajo', label: 'Diné Bizaad', value: 'nav' },
        { name: 'Northern Ndebele', label: 'isiNdebele', value: 'nde' },
        { name: 'Nepali', label: 'नेपाली', value: 'nep' },
        { name: 'Ndonga', label: 'Owambo', value: 'ndo' },
        { name: 'Norwegian Bokmål', label: 'Norsk (Bokmål)', value: 'nob' },
        { name: 'Norwegian Nynorsk', label: 'Norsk (Nynorsk)', value: 'nno' },
        { name: 'Norwegian', label: 'Norsk', value: 'nor' },
        { name: 'Nuosu', label: 'ꆈꌠ꒿ Nuosuhxop', value: 'iii' },
        { name: 'Southern Ndebele', label: 'isiNdebele', value: 'nbl' },
        { name: 'Occitan', label: 'Occitan', value: 'oci' },
        { name: 'Ojibwe', label: 'ᐊᓂᔑᓈᐯᒧᐎᓐ', value: 'oji' },
        { name: 'Old Church Slavonic', label: 'Словѣ́ньскъ', value: 'chu' },
        { name: 'Oromo', label: 'Afaan Oromoo', value: 'orm' },
        { name: 'Oriya', label: 'ଓଡି଼ଆ', value: 'ori' },
        { name: 'Ossetian', label: 'Ирон æвзаг', value: 'oss' },
        { name: 'Panjabi', label: 'ਪੰਜਾਬੀ', value: 'pan' },
        { name: 'Pāli', label: 'पाऴि', value: 'pli' },
        { name: 'Persian', label: 'فارسی', value: 'fas' },
        { name: 'Polish', label: 'Polski', value: 'pol' },
        { name: 'Pashto', label: 'پښتو', value: 'pus' },
        { name: 'Portuguese', label: 'Português', value: 'por' },
        { name: 'Quechua', label: 'Runa Simi', value: 'que' },
        { name: 'Romansh', label: 'Rumantsch', value: 'roh' },
        { name: 'Kirundi', label: 'Kirundi', value: 'run' },
        { name: 'Romanian', label: 'Română', value: 'ron' },
        { name: 'Russian', label: 'Русский', value: 'rus' },
        { name: 'Sanskrit', label: 'संस्कृतम्', value: 'san' },
        { name: 'Sardinian', label: 'Sardu', value: 'srd' },
        { name: 'Sindhi', label: 'سنڌي‎', value: 'snd' },
        { name: 'Northern Sami', label: 'Sámegiella', value: 'sme' },
        { name: 'Samoan', label: 'Gagana Sāmoa', value: 'smo' },
        { name: 'Sango', label: 'Sängö', value: 'sag' },
        { name: 'Serbian', label: 'Српски', value: 'srp' },
        { name: 'Gaelic', label: 'Gàidhlig', value: 'gla' },
        { name: 'Shona', label: 'ChiShona', value: 'sna' },
        { name: 'Sinhala', label: 'සිංහල', value: 'sin' },
        { name: 'Slovak', label: 'Slovenčina', value: 'slk' },
        { name: 'Slovene', label: 'Slovenščina', value: 'slv' },
        { name: 'Somali', label: 'Soomaaliga', value: 'som' },
        { name: 'Southern Sotho', label: 'Sesotho', value: 'sot' },
        { name: 'Spanish', label: 'Español', value: 'spa' },
        { name: 'Sundanese', label: 'Basa Sunda', value: 'sun' },
        { name: 'Swahili', label: 'Kiswahili', value: 'swa' },
        { name: 'Swati', label: 'SiSwati', value: 'ssw' },
        { name: 'Swedish', label: 'Svenska', value: 'swe' },
        { name: 'Tamil', label: 'தமிழ்', value: 'tam' },
        { name: 'Telugu', label: 'తెలుగు', value: 'tel' },
        { name: 'Tajik', label: 'Тоҷикӣ', value: 'tgk' },
        { name: 'Thai', label: 'ภาษาไทย', value: 'tha' },
        { name: 'Tigrinya', label: 'ትግርኛ', value: 'tir' },
        { name: 'Tibetan Standard', label: 'བོད་ཡིག', value: 'bod' },
        { name: 'Turkmen', label: 'Türkmençe', value: 'tuk' },
        { name: 'Tagalog', label: 'Tagalog', value: 'tgl' },
        { name: 'Tswana', label: 'Setswana', value: 'tsn' },
        { name: 'Tonga', label: 'faka Tonga', value: 'ton' },
        { name: 'Turkish', label: 'Türkçe', value: 'tur' },
        { name: 'Tsonga', label: 'Xitsonga', value: 'tso' },
        { name: 'Tatar', label: 'Татарча', value: 'tat' },
        { name: 'Twi', label: 'Twi', value: 'twi' },
        { name: 'Tahitian', label: 'Reo Mā’ohi', value: 'tah' },
        { name: 'Uyghur', label: 'ئۇيغۇرچه', value: 'uig' },
        { name: 'Ukrainian', label: 'Українська', value: 'ukr' },
        { name: 'Urdu', label: 'اردو', value: 'urd' },
        { name: 'Uzbek', label: 'O‘zbek', value: 'uzb' },
        { name: 'Venda', label: 'Tshivenḓa', value: 'ven' },
        { name: 'Vietnamese', label: 'Tiếng Việt', value: 'vie' },
        { name: 'Volapük', label: 'Volapük', value: 'vol' },
        { name: 'Walloon', label: 'Walon', value: 'wln' },
        { name: 'Welsh', label: 'Cymraeg', value: 'cym' },
        { name: 'Wolof', label: 'Wolof', value: 'wol' },
        { name: 'Western Frisian', label: 'Frysk', value: 'fry' },
        { name: 'Xhosa', label: 'isiXhosa', value: 'xho' },
        { name: 'Yiddish', label: 'ייִדיש', value: 'yid' },
        { name: 'Yoruba', label: 'Yorùbá', value: 'yor' },
        { name: 'Zhuang', label: 'Cuengh', value: 'zha' },
        { name: 'Zulu', label: 'isiZulu', value: 'zul' }]
    }
  }
}
